### ISSUE TITLE
use engine command and had this error: dynamic_load: init failed

### ISSUE THREAD

**Issue by Hannah336** [open-quantum-safe/oqs-engine#3]
I run the code on Ubuntu 20.0.4, oqse_test acted as expected. And I test the engine liboqse.so with following command:
openssl engine -t -c `pwd`/lib/liboqse.so
I met 2 errors:
dynamic_load: init failed: ../crypto/engine/eng_dyn.c:485
engine routines: ENGINE_by_id: no such engine: ../crypto/engine/eng_list.c: 334: id=/home/yh/oqs-engine/build/lib/liboqse.so
Is there something wrong? How to fix it?

**Comment by dstebila** [comment]
Hi Hannah, we are not in a position to support the OQS OpenSSL engine any more, as it was contributed by a third-aprty provider and we don't have expertise with it. Sorry we won't be able to help you.
